// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: tages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *AddPictureRequest) Reset() {
	*x = AddPictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPictureRequest) ProtoMessage() {}

func (x *AddPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPictureRequest.ProtoReflect.Descriptor instead.
func (*AddPictureRequest) Descriptor() ([]byte, []int) {
	return file_tages_proto_rawDescGZIP(), []int{0}
}

func (x *AddPictureRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type AddPictureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPictureResponse) Reset() {
	*x = AddPictureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPictureResponse) ProtoMessage() {}

func (x *AddPictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPictureResponse.ProtoReflect.Descriptor instead.
func (*AddPictureResponse) Descriptor() ([]byte, []int) {
	return file_tages_proto_rawDescGZIP(), []int{1}
}

var File_tages_proto protoreflect.FileDescriptor

var file_tages_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22,
	0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x50, 0x0a, 0x05, 0x54, 0x61, 0x67, 0x65, 0x73, 0x12, 0x47,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x18, 0x2e, 0x74, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tages_proto_rawDescOnce sync.Once
	file_tages_proto_rawDescData = file_tages_proto_rawDesc
)

func file_tages_proto_rawDescGZIP() []byte {
	file_tages_proto_rawDescOnce.Do(func() {
		file_tages_proto_rawDescData = protoimpl.X.CompressGZIP(file_tages_proto_rawDescData)
	})
	return file_tages_proto_rawDescData
}

var file_tages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tages_proto_goTypes = []interface{}{
	(*AddPictureRequest)(nil),  // 0: tages.AddPictureRequest
	(*AddPictureResponse)(nil), // 1: tages.AddPictureResponse
}
var file_tages_proto_depIdxs = []int32{
	0, // 0: tages.Tages.GettingPicture:input_type -> tages.AddPictureRequest
	1, // 1: tages.Tages.GettingPicture:output_type -> tages.AddPictureResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tages_proto_init() }
func file_tages_proto_init() {
	if File_tages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPictureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tages_proto_goTypes,
		DependencyIndexes: file_tages_proto_depIdxs,
		MessageInfos:      file_tages_proto_msgTypes,
	}.Build()
	File_tages_proto = out.File
	file_tages_proto_rawDesc = nil
	file_tages_proto_goTypes = nil
	file_tages_proto_depIdxs = nil
}
